title: DSA # title which appears for the website
email: mittalsagar006@gmail.com
description: > # short discription of your website. It is helpful for making your website more discoverable and appears while previewing your website.
    A course website for 3rd sem. DSA subject
 
baseurl: "3-DSA"   # specify the subpath of your site
url: "https://sagarmittal1.github.io" # the base hostname & protocol for YOUR site, e.g. http://example.com
twitter_username: sagar_mittal5 # twitter Username
github_username: sagarmittal1 # GitHub Username
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
